services:
  chat:
    build: .
    container_name: chat
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LLM_API_BASE
      - EMBED_API_BASE
      - API_KEY
      - MODEL
      - MAX_TOKENS
      - TEMPERATURE
      - FREQUENCY_PENALTY
      - PRESENCE_PENALTY
      - STEP_THRESHOLD
      - MEM0_DIR
      - EMBEDDING_MODEL
    depends_on:
      - redis

  redis:
    container_name: chat-database
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
