services:
  chat:
    build: .
    container_name: chat
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LLM_API_BASE
      - API_KEY
      - MODEL
      - MAX_TOKENS
      - TEMPERATURE
      - FREQUENCY_PENALTY
      - PRESENCE_PENALTY
      - STEP_THRESHOLD
      - EMBEDDING_CACHE_DIR=/app/embedding_cache
      - HF_TOKEN
    volumes:
      - uploads_data:/app/uploads
      - embedding_cache:/app/embedding_cache
    depends_on:
      - redis
    networks:
      - proxy-nw

  redis:
    container_name: chat-database
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  proxy-nw:
    external: true

volumes:
  redis_data:
  uploads_data:
  embedding_cache:
